# Generated by Django 4.0.1 on 2022-11-13 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('have_any_video', models.BooleanField(default=False)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('url', models.URLField()),
                ('content_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contentt', to='my_app.content')),
            ],
        ),
    ]
