# Generated by Django 4.0.1 on 2022-11-13 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_gallary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallary',
            name='content_for',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contentt', to='my_app.content'),
        ),
    ]
