# Generated by Django 4.0.1 on 2022-11-13 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_gallary_content_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallary',
            name='url',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='gallary',
            name='content_for',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Media', to='my_app.content'),
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('content_for', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Gallary', to='my_app.gallary')),
            ],
        ),
    ]
