# Generated by Django 4.0.1 on 2022-11-13 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_gallary_url_remove_gallary_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='content_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallary', to='my_app.gallary'),
        ),
    ]
