# Generated by Django 4.0.1 on 2022-11-13 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_photos_content_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='content_for',
            new_name='content_f',
        ),
        migrations.AlterField(
            model_name='gallary',
            name='content_for',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='my_app.content'),
        ),
    ]
