# Generated by Django 4.1 on 2022-11-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_catagory_remove_photos_content_f_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
